[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tsensor"
version = "0.1.0"
dependencies = [
    "flask",
    "pyserial",
    "loguru",
    "toml",
    "google-api-python-client",
    "google-auth-oauthlib",
    "google-auth-httplib2",
    "parsel",
    "pytest",
    "pytest-mock",
    "numpy",
    "matplotlib",
    "scipy",
    "pygame",
    "ovld",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
filterwarnings = [
    "ignore::FutureWarning:google.api_core._python_version_support"
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
